### ISSUE TITLE
the site keep waiting on evaluation after code submission

### ISSUE THREAD

**Issue by rayhsieh** [wenchin77/coding-fight-club#11]

**Comment by wenchin77** [comment]
Hi! Thanks a lot for reporting the issue. Could you please elaborate how I can reproduce this issue? (eg. what buttons you click: **Submit** on the top right or **Run Code** on the bottom right and what the sequence is)

![Screen Shot 2020-03-12 at 4 23 20 PM](https://user-images.githubusercontent.com/56374865/77036836-f90f1380-69ea-11ea-9beb-88e7ed8b5705.png)

Best regards
